// Generated by Xata Codegen 0.25.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "palettes",
    columns: [
      { name: "primary", type: "string" },
      { name: "secondary", type: "string" },
      { name: "additional_colors", type: "multiple" },
      { name: "name", type: "string" },
      { name: "created_by", type: "string" },
      { name: "is_published", type: "bool", defaultValue: "false" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Palettes = InferredTypes["palettes"];
export type PalettesRecord = Palettes & XataRecord;

export type DatabaseSchema = {
  palettes: PalettesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Cosmin-s-workspace-2d11qi.eu-central-1.xata.sh/db/cxmindigital",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
